### ISSUE TITLE
Tags display "0" in Yomichan version 21.9.30.1

### ISSUE THREAD

**Issue by stephenmk** [stephenmk/yomichan-jlpt-vocab#1]
The newest version of Yomichan allows users to sort by the frequencies provided by frequency dictionaries. The ability to store generic string values in frequency dictionaries was therefore removed.

https://github.com/FooSoft/yomichan/pull/1943

https://github.com/FooSoft/yomichan/issues/1984

**Comment by stephenmk** [comment]
Temporarily solution implemented in release [rev.JLPT;2021-10-14](https://github.com/stephenmk/yomichan-jlpt-vocab/releases/tag/rev.JLPT%3B2021-10-14)

**Comment by toasted-nutbread** [comment]
FYI, once this fix is released in a patch, you will be able to explicitly specify both a string and numeric value for frequencies.

https://github.com/FooSoft/yomichan/pull/1989
